# Используем базовый образ
FROM eclipse-temurin:21-jdk-alpine
# Создаем папку для приложения
WORKDIR /app
# Копируем наш файл (даже если он пустой, для теста пойдет)
COPY . .
# Заглушка для команды запуска
CMD ["echo", "Container is running"]